#!/bin/sh

# Please use DMD 2.077.1 or below when building the documentation.
#
# DMD 2.078.0 and up causes lots of duplicated symbols in the documentation.
# (See: https://github.com/rejectedsoftware/ddox/issues/208 )
#
# DMD 2.086.0 and up cause errors when building the docs because
# gen-package-version and Scriptlike need updated.

rdmd --build-only -c -Isource -Dddocs_tmp -X -Xfdocs/docs.json -version=MySQLDocs --force source/mysql/package.d
rm -rf docs_tmp
rm source/mysql/package.o

dub --version
dub run gen-package-version -- mysql --ddoc=ddoc --src=source
rm source/mysql/packageVersion.d

echo Building ddox...
cd ./ddox
dub build
cd ..
echo Done building ddox...

echo ddox filter...
./ddox/ddox -- filter docs/docs.json --min-protection Public
echo ddox generate-html...
./ddox/ddox -- generate-html docs/docs.json docs/public --navigation-type=ModuleTree --override-macros=ddoc/macros.ddoc --override-macros=ddoc/packageVersion.ddoc
