#!/bin/sh

# GDC doesn't autocreate the dir (and git doesn't beleive in empty dirs)
mkdir -p bin

if [ "$USE_UNIT_THREADED" = "true" ]; then
	dub run -c unittest-vibe-ut -- -t "$@"
else
	dub test -c unittest-vibe
fi
