#!/bin/sh

. ./find-rdmd.sh

echo Using:
echo "  RDMD=$RDMD"
echo "  DMD=$DMD"

# GDC doesn't autocreate the dir (and git doesn't beleive in empty dirs)
mkdir -p bin

if [ "$CORE_PHOBOS_TESTS_ONLY" = "true" ]; then
	MSG_SUFFIX=' (core tests only)'
	DEBUG_TESTS_ID=MYSQLN_CORE_TESTS
else
	MSG_SUFFIX=''
	DEBUG_TESTS_ID=MYSQLN_TESTS
fi

if [ "$USE_UNIT_THREADED" = "true" ]; then
	MSG_SUFFIX="$MSG_SUFFIX (unit-threaded)"
	UT_VER=0.7.45
	UT_SUFFIX='-ut'
	UT_ARGS=-version=MYSQLN_TESTS_NO_MAIN -version=Have_unit_threaded -Iunit-threaded-${UT_VER}/unit-threaded/source/ --extra-file=unit-threaded-${UT_VER}/unit-threaded/libunit-threaded.a --exclude=unit_threaded
	D_FILE=bin/ut.d

	# Setup unit-threaded
	dub fetch unit-threaded --version=${UT_VER} --cache=local
	cd unit-threaded-${UT_VER}/unit-threaded
	dub build -c gen_ut_main
	dub build -c library
	cd ../..
	unit-threaded-${UT_VER}/unit-threaded/gen_ut_main -f bin/ut.d
else
	D_FILE=source/mysql/package.d
fi

echo Compiling Phobos-socket tests${MSG_SUFFIX}...
$RDMD --compiler=$DMD --build-only -g -unittest $UT_ARGS -debug=$DEBUG_TESTS_ID -ofbin/mysqln-tests-phobos${UT_SUFFIX} -Isource $D_FILE && echo Running Phobos-socket tests${MSG_SUFFIX}... && bin/mysqln-tests-phobos${UT_SUFFIX} "$@"
