#!/bin/sh

. ./find-rdmd.sh

echo Using:
echo "  RDMD=$RDMD"
echo "  DMD=$DMD"

# GDC doesn't autocreate the dir (and git doesn't beleive in empty dirs)
mkdir -p bin

if [ "$CORE_PHOBOS_TESTS_ONLY" = "true" ]; then
	MSG_SUFFIX=' (core tests only)'
	DEBUG_TESTS_ID=MYSQLN_CORE_TESTS
else
	MSG_SUFFIX=''
	DEBUG_TESTS_ID=MYSQLN_TESTS
fi

echo Compiling Phobos-socket tests${MSG_SUFFIX}...
$RDMD --compiler=$DMD --build-only -g -unittest -debug=$DEBUG_TESTS_ID -ofbin/mysqln-tests-phobos -Isource source/mysql/package.d && echo Running Phobos-socket tests${MSG_SUFFIX}... && bin/mysqln-tests-phobos
